-- =============================================================
-- GYM SOFTWARE: SaaS ADMIN & APPROVAL SCHEMA (Final Fixed)
-- =============================================================

-- 1. CLEAN SLATE (Delete all operational tables from Supabase)
DROP VIEW IF EXISTS public.active_members CASCADE;
DROP VIEW IF EXISTS public.monthly_reports CASCADE;
DROP VIEW IF EXISTS public.active_members_stats CASCADE;

DROP TABLE IF EXISTS public.attendance CASCADE;
DROP TABLE IF EXISTS public.payments CASCADE;
DROP TABLE IF EXISTS public.members CASCADE;
DROP TABLE IF EXISTS public.classes CASCADE;
DROP TABLE IF EXISTS public.supplements CASCADE;
DROP TABLE IF EXISTS public.cardio_sessions CASCADE;
DROP TABLE IF EXISTS public.cardio_subscriptions CASCADE;
DROP TABLE IF EXISTS public.training_plans CASCADE;
DROP TABLE IF EXISTS public.invoices CASCADE;
DROP TABLE IF EXISTS public.gym_settings CASCADE;

-- 2. SaaS TABLES SETUP
CREATE TABLE IF NOT EXISTS public.software_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    slug TEXT NOT NULL UNIQUE,
    price NUMERIC(12,2) NOT NULL,
    duration_months INTEGER NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

INSERT INTO public.software_plans (name, slug, price, duration_months, description)
VALUES 
('Monthly Plan', 'monthly', 5000, 1, 'Standard monthly subscription for early-stage gyms'),
('Bi-Annual Plan', 'six_months', 25000, 6, 'Pay for 6 months and save 5000!'),
('Annual VIP Plan', 'yearly', 45000, 12, 'Best value! Full access for one year with massive savings')
ON CONFLICT (slug) DO UPDATE SET 
    price = EXCLUDED.price,
    description = EXCLUDED.description;

CREATE TABLE IF NOT EXISTS public.super_admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    full_name TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='super_admins' AND column_name='full_name') THEN
        ALTER TABLE public.super_admins ADD COLUMN full_name TEXT;
    END IF;
END $$;

INSERT INTO public.super_admins (email, full_name)
VALUES ('owner@gympro.com', 'System Owner')
ON CONFLICT (email) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.admin_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    full_name TEXT NOT NULL,
    gym_name TEXT NOT NULL,
    plan_type TEXT NOT NULL CHECK (plan_type IN ('monthly', 'six_months', 'yearly')),
    plan_price NUMERIC(12,2) NOT NULL,
    payment_status TEXT NOT NULL DEFAULT 'pending' CHECK (payment_status IN ('pending', 'approved', 'rejected')),
    approval_status TEXT NOT NULL DEFAULT 'pending' CHECK (approval_status IN ('pending', 'approved', 'rejected')),
    is_active BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_admin_accounts_email ON public.admin_accounts(email);
CREATE INDEX IF NOT EXISTS idx_admin_accounts_approval ON public.admin_accounts(approval_status);

-- 3. HELPER FUNCTIONS
CREATE OR REPLACE FUNCTION public.is_super_admin()
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN EXISTS (SELECT 1 FROM public.super_admins sa WHERE lower(sa.email) = lower(auth.jwt() ->> 'email'));
END;
$$;

-- 4. SECURITY (RLS)
ALTER TABLE public.software_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.super_admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_accounts ENABLE ROW LEVEL SECURITY;

-- Drop Policies if exist before creating (To avoid policy already exists error)
DROP POLICY IF EXISTS "Public read software_plans" ON public.software_plans;
DROP POLICY IF EXISTS "Users view own admin_account" ON public.admin_accounts;
DROP POLICY IF EXISTS "Super Admins manage all" ON public.admin_accounts;
DROP POLICY IF EXISTS "Super Admins manage all admin_accounts" ON public.admin_accounts;

CREATE POLICY "Public read software_plans" ON public.software_plans FOR SELECT USING (true);
CREATE POLICY "Users view own admin_account" ON public.admin_accounts 
FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Super Admins manage all" ON public.admin_accounts 
FOR ALL TO authenticated USING (public.is_super_admin()) WITH CHECK (public.is_super_admin());

-- 5. TRIGGER ON SIGNUP
CREATE OR REPLACE FUNCTION public.handle_new_admin_signup()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    IF NEW.raw_user_meta_data ->> 'role' = 'admin_owner' THEN
        INSERT INTO public.admin_accounts (
            user_id, email, full_name, gym_name, plan_type, plan_price
        ) VALUES (
            NEW.id,
            NEW.email,
            COALESCE(NEW.raw_user_meta_data ->> 'full_name', 'Gym Owner'),
            COALESCE(NEW.raw_user_meta_data ->> 'gym_name', 'New Gym'),
            COALESCE(NEW.raw_user_meta_data ->> 'plan_type', 'monthly'),
            COALESCE((NEW.raw_user_meta_data ->> 'plan_price')::numeric, 5000)
        ) ON CONFLICT (user_id) DO NOTHING;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_admin_signup();

-- 6. ENABLE REALTIME (With check to avoid error if already added)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' 
        AND schemaname = 'public' 
        AND tablename = 'software_plans'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.software_plans;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' 
        AND schemaname = 'public' 
        AND tablename = 'admin_accounts'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.admin_accounts;
    END IF;
END $$;
